[?1049h[>4;2m[?1h=[?2004h[?1004h[1;43r[?12h[?12l[22;2t[22;1t[27m[23m[29m[m[H[2J[?25l[43;1H"/var/folders/t3/ljthm3yx12l0qb_kxrxbkq7c0000gn/T/kubectl-edit-773272914.yaml" 110L, 4018B[1;1H# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |[11;7H{"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"adservice"},"name":"adservice","namespace":"default"},"spec":{"selector":{"matchLabels":{{[12;1H"app":"adservice"}},"template":{"metadata":{"labels":{"app":"adservice"}},"spec":{"containers":[{"env":[{"name":"PORT","value":"9555"}],"image":"730335571577.dkr.ecr.us-west-2.amazonawss[13;1H.com/online-boutique:adservice","livenessProbe":{"grpc":{"port":9555},"initialDelaySeconds":20,"periodSeconds":15},"name":"server","ports":[{"containerPort":9555}],"readinessProbe":{"grr[14;1Hpc":{"port":9555},"initialDelaySeconds":20,"periodSeconds":15},"resources":{"limits":{"cpu":"300m","memory":"300Mi"},"requests":{"cpu":"200m","memory":"180Mi"}},"securityContext":{"alloo[15;1HwPrivilegeEscalation":false,"capabilities":{"drop":["ALL"]},"privileged":false,"readOnlyRootFilesystem":true}}],"securityContext":{"fsGroup":1000,"runAsGroup":1000,"runAsNonRoot":true,""[16;1HrunAsUser":1000},"serviceAccountName":"adservice","terminationGracePeriodSeconds":5}}}}
  creationTimestamp: "2024-12-02T17:44:38Z"
  generation: 1
  labels:
    app: adservice
  name: adservice
  namespace: default
  resourceVersion: "22499"
  uid: 978aeb18-f726-4ea1-96bd-0c2a3ee3140b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:[31;7Happ: adservice
  strategy:
    rollingUpdate:[34;7HmaxSurge: 25%[35;7HmaxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:[39;7HcreationTimestamp: null[40;7Hlabels:[41;9Happ: adservice
    spec:[1;1H[?25h[?4m[43;1H[?2004l[>4;m[23;2t[23;1t[43;1H[K[43;1H[?1004l[?2004l[?1l>[?1049l[>4;m